### ISSUE TITLE
Deserializing DataStore does not work correctly

### ISSUE THREAD

**Issue by eleanor-em** [microsoft/electionguard-python#316]
## Bug Report
This issue was found using ElectionGuard 1.1.15 as published to PyPI, with Python 3.8.2. (Also tested with the current `main` version.)

**Expected Behavior**
Since many ElectionGuard classes containing attributes of type `DataStore[A, B]` inherit from `Serializable,` it should be possible to serialize and deserialize `DataStore` using `read_json` and `write_json`.

**Actual Behavior**
`DataStore` (which takes two type parameters) uses the `jsons` method to deserialize `Iterable`. However, `typing.Iterable` can only take one type parameter, causing the deserializer to fail with an exception.

The following minimal example demonstrates the problem:
```py
from electionguard.data_store import DataStore
from electionguard.serializable import read_json, write_json

foo = {
    "a": 1,
    "b": 2
}

ds = DataStore()
for (key, val) in foo.items():
    ds.set(key, val)

ds2 = read_json(write_json(ds), DataStore[str, int])
```
This fails with the error:
```
Traceback (most recent call last):
  File "/Users/eleanor/code/righttoask-trustee/venv/lib/python3.8/site-packages/jsons/_load_impl.py", line 111, in _do_load
    result = deserializer(json_obj, cls, **kwargs)
  File "/Users/eleanor/code/righttoask-trustee/venv/lib/python3.8/site-packages/jsons/deserializers/default_iterable.py", line 29, in default_iterable_deserializer
    result = naked_cls(list_)
TypeError: __init__() takes 1 positional argument but 2 were given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/test.py", line 13, in <module>
    ds2 = read_json(write_json(ds), DataStore)
  File "/Users/eleanor/code/righttoask-trustee/venv/lib/python3.8/site-packages/electionguard/serializable.py", line 176, in read_json
    return cast(_T, loads(data, class_out))
  File "/Users/eleanor/code/righttoask-trustee/venv/lib/python3.8/site-packages/jsons/_load_impl.py", line 153, in loads
    return load(obj, cls, *args, **kwargs)
  File "/Users/eleanor/code/righttoask-trustee/venv/lib/python3.8/site-packages/jsons/_load_impl.py", line 99, in load
    return _do_load(json_obj, deserializer, cls, initial, **kwargs_)
  File "/Users/eleanor/code/righttoask-trustee/venv/lib/python3.8/site-packages/jsons/_load_impl.py", line 118, in _do_load
    raise DeserializationError(message, json_obj, cls) from err
jsons.exceptions.DeserializationError: Could not deserialize value "[['a', 1], ['b', 2]]" into "electionguard.data_store.DataStore". __init__() takes 1 positional argument but 2 were given
~/code/righttoask-trustee on main +11 !6 ?3 ❯ python src/test.py                                                                                                    righttoask-trustee at 14:30:04
Traceback (most recent call last):
  File "/Users/eleanor/code/righttoask-trustee/venv/lib/python3.8/site-packages/jsons/_load_impl.py", line 111, in _do_load
    result = deserializer(json_obj, cls, **kwargs)
  File "/Users/eleanor/code/righttoask-trustee/venv/lib/python3.8/site-packages/jsons/deserializers/default_iterable.py", line 24, in default_iterable_deserializer
    cls_ = IterableType[cls.__args__]
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/typing.py", line 261, in inner
    return func(*args, **kwds)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/typing.py", line 683, in __getitem__
    _check_generic(self, params)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/typing.py", line 215, in _check_generic
    raise TypeError(f"Too {'many' if alen > elen else 'few'} parameters for {cls};"
TypeError: Too many parameters for typing.Iterable; actual 2, expected 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/test.py", line 13, in <module>
    ds2 = read_json(write_json(ds), DataStore[str, int])
  File "/Users/eleanor/code/righttoask-trustee/venv/lib/python3.8/site-packages/electionguard/serializable.py", line 176, in read_json
    return cast(_T, loads(data, class_out))
  File "/Users/eleanor/code/righttoask-trustee/venv/lib/python3.8/site-packages/jsons/_load_impl.py", line 153, in loads
    return load(obj, cls, *args, **kwargs)
  File "/Users/eleanor/code/righttoask-trustee/venv/lib/python3.8/site-packages/jsons/_load_impl.py", line 99, in load
    return _do_load(json_obj, deserializer, cls, initial, **kwargs_)
  File "/Users/eleanor/code/righttoask-trustee/venv/lib/python3.8/site-packages/jsons/_load_impl.py", line 118, in _do_load
    raise DeserializationError(message, json_obj, cls) from err
jsons.exceptions.DeserializationError: Could not deserialize value "[['a', 1], ['b', 2]]" into "electionguard.data_store.DataStore". Too many parameters for typing.Iterable; actual 2, expected 1
```

**Comment by eleanor-em** [comment]
This is a hacky work-around that does successfully deserialize `DataStore`.
```py
def load_data_store(data, ty):
    obj = json.loads(data)
    ids = [elem[0] for elem in obj]
    details = [read_json(json.dumps(elem[1]), ty) for elem in obj]
    ret = DataStore()
    ret._store = dict(zip(ids, details))
    return ret
```

**Comment by keithrfung** [comment]
@eleanor-em This should not actually be a problem going forward. The `DataStore` should NOT be getting deserialized. The `Guardian` itself should not be getting serialized at any point.
