### ISSUE TITLE
🐞 Sample data generation failed

### ISSUE THREAD

**Issue by ramsdell** [microsoft/electionguard-python#650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I downloaded and built the code on MacOS 12.4 today.  The output of the build process showed no errors.  I attempted to build a sample using make.  Here is what happened.

```
$ make SAMPLE_BALLOT_COUNT=100 generate-sample-data
🔁 GENERATE Sample Data
poetry run python3 src/electionguard_tools/scripts/sample_generator.py -m "hamilton-general" -n 100 -s 50
/usr/local/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
[52500:2022-06-06 13:46:16,850]:ERROR:elgamal.py.decrypt:#L143: MAC verification failed in decryption.
Traceback (most recent call last):
  File "/Users/ramsdell/rep/electionguard-python/src/electionguard_tools/scripts/sample_generator.py", line 249, in <module>
    ElectionSampleDataGenerator().generate(
  File "/Users/ramsdell/rep/electionguard-python/src/electionguard_tools/scripts/sample_generator.py", line 83, in generate
    ) = self.election_factory.get_sample_manifest_with_encryption_context(
  File "/Users/ramsdell/rep/electionguard-python/src/electionguard_tools/factories/election_factory.py", line 128, in get_sample_manifest_with_encryption_context
    KeyCeremonyOrchestrator.perform_full_ceremony(guardians, mediator)
  File "/Users/ramsdell/rep/electionguard-python/src/electionguard_tools/helpers/key_ceremony_orchestrator.py", line 29, in perform_full_ceremony
    KeyCeremonyOrchestrator.perform_round_3(guardians, mediator)
  File "/Users/ramsdell/rep/electionguard-python/src/electionguard_tools/helpers/key_ceremony_orchestrator.py", line 69, in perform_round_3
    guardian.verify_election_partial_key_backup(
  File "/Users/ramsdell/rep/electionguard-python/src/electionguard/guardian.py", line 368, in verify_election_partial_key_backup
    return verify_election_partial_key_backup(
  File "/Users/ramsdell/rep/electionguard-python/src/electionguard/key_ceremony.py", line 266, in verify_election_partial_key_backup
    get_optional(bytes_optional)
  File "/Users/ramsdell/rep/electionguard-python/src/electionguard/utils.py", line 72, in get_optional
    assert optional is not None, "Unwrap called on None"
AssertionError: Unwrap called on None
make: *** [generate-sample-data] Error 1
$ 
```

### Expected Behavior

Sample data should be generated.

### Environment

```markdown
- OS: MacOS 12.4.
```

**Comment by keithrfung** [comment]
CC @lprichar and see https://github.com/microsoft/electionguard-python/issues/618

**Comment by ramsdell** [comment]
May I suggest that a comment be included in the Makefile for each deprecated make target?  Otherwise, how is a newbie to know?  Also, Line 88 has a tab in it when it should not.

**Comment by lprichar** [comment]
Excellent points @ramsdell
